channels:
  - conda-forge
  - manics
dependencies:
  - numpy
  - fabio
  - h5py
  - scipy
  - silx
  - pyqt
  - matplotlib
  - bash_kernel
  - ipywidgets
  - ipympl
  - rise
  - websockify
  - pip:
    - h5glance
    - -e git://github.com/yuvipanda/jupyter-desktop-server.git#egg=jupyter-desktop-server
