channels:
  - conda-forge
  - manics
dependencies:
  - numpy
  - fabio
  - h5py
  - scipy
  - silx
  - pyqt
  - matplotlib
  - bash_kernel
  - ipywidgets
  - ipympl
  - rise
  - websockify
  - pip:
      - h5glance
      - jupyter-remote-desktop-proxy
